return {
  "williamboman/mason.nvim",
  version = "1.11.0",
  event = "LazyFile",
  opts = {
    ensure_installed = {
      "tailwindcss-language-server",
      "lua-language-server",
      "stylua",
      -- "dart-debug-adapter",
      "html-lsp",
      "css-lsp",
      "prettier",
      -- "prettierd",
      "pyright",
      "vtsls",
      -- "typescript-language-server",
      -- "black",
      -- "isort",
      -- "flake8",
      -- "eslint_d",
      "eslint-lsp",
      "emmet-language-server",
      "js-debug-adapter",
    },
    ui = { border = "rounded" },
  },
}
