return {
  'williamboman/mason.nvim',
  version = '1.11.0',
  event = 'LazyFile',
  opts = {
    ensure_installed = {
      'tailwindcss-language-server',
      'lua-language-server',
      'stylua',
      -- "dart-debug-adapter",
      'html-lsp',
      'css-lsp',
      'prettier',
      'pyright',
      -- "vtsls",
      'prisma-language-server',
      'eslint-lsp',
      'emmet-language-server',
      'js-debug-adapter',
      'taplo',
      'json-lsp',
    },
    ui = { border = 'rounded' },
  },
}
